version: '3.1'
services:
    mariadb:
        container_name: phpcoursem5.mariadb
        restart: unless-stopped
        image: 'mariadb:10.6'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=user
            - MYSQL_PASSWORD=123
        ports:
            - '8891:3306'

    webserver:
        container_name: phpcoursem5.webserver
        restart: unless-stopped
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8889:80'

    php-fpm:
        container_name: phpcoursem5.php-fpm
        restart: unless-stopped
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
