CREATE DATABASE IF NOT EXISTS shorten_url;

USE shorten_url;

CREATE TABLE IF NOT EXISTS urls (
    id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    short_url VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE urls
    ADD COLUMN IF NOT EXISTS visits_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_visit DATETIME;
