version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        container_name: lesson3_webserver
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '9000:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: lesson3_php
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

    composer:
        image: 'composer:latest'
        container_name: lesson3_composer
        command: [ "composer", "update" ]
        volumes:
            - '.:/app'
