controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_index:
    path: /user/{name}
    controller: App\Controller\UserController::index

order_index:
    path: /order/{name}
    controller: App\Controller\OrderController
    methods: GET
