# fly.toml app configuration file generated for payment-api-module5 on 2023-10-05T17:28:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "payment-api-module5"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
